```{r}
library(tidyverse)
library(kableExtra)
library(dplyr)
library(zoo)
library(readxl)
library(factoextra)
library(cluster)
library(cartogram)
library(hrbrthemes)
library(viridis)
library(plotly)
library(pheatmap)
library(heatmaply)
```

```{r}
#reading and wrangling
rawData <- read.csv("GIIHDI.csv")

#filtering
heat <- rawData %>% 
  arrange(desc(X2021)) %>% 
  slice(1:30) %>% 
  arrange(desc(HDI_rank)) %>% 
  rename(adoloscentBirthrate = Adol_birthrate) %>% 
  rename(politicalParticipation = Parliament) %>% 
  rename(educationLevel = Secondary) %>% 
  rename(labourParticipation = LF_Part)
  

#standardising
#heat$adoloscentBirthrate <- scale(heat$Adol_birthrate)
#heat$parlimentaryParticipation <- scale(heat$Parliament)
#heat$secondaryEducation <- scale(heat$Secondary)
#heat$labourParticipation <- scale(heat$LF_Part)
  
```

```{r}
#crwating matrix
matrix <- heat
rownames(matrix) <- matrix[,1]
matrix <- matrix %>% arrange(desc(X2021))
matrix <- matrix %>% dplyr::select(-Country, -HDI_value, -HDI_rank, -GII_value, -GII_rank, -X2021)
matrix <- as.matrix(matrix)
```

```{r}
library(heatmaply)

# create a color scale and legend labels
#colors <- c("#FF8A8A", "#FF5C5C", "#D10000", "#A30000", "#750000")
#legend_labels <- c("Lowest", "Low", "Medium", "High", "Highest")

p <- heatmaply(matrix, 
        dendrogram = TRUE,
        show_colorbar = TRUE,
        width = 1000,
        height = 600,
        xlab = "", ylab = "", 
        main = "",
        scale = "column",
        margins = c(60,100,40,20),
        grid_color = "white",
        grid_width = 0.00001,
        titleX = FALSE,
        hide_colorbar = TRUE,
        branches_lwd = 0.2,
        fontsize_row = 5, fontsize_col = 5,
        labCol = colnames(matrix),
        labRow = rownames(matrix),
        heatmap_layers = theme(axis.line=element_blank()),
        legend = TRUE,
        legend_side = "right"
        )

print(p)
```



