Needed Packages
```{r}
library(tidyverse)
library(kableExtra)
library(dplyr)
library(zoo)
library(ggrepel)
library(broom)
library(GGally)
library(purrr)

library(gapminder)
```

```{r}
#CSV to table
#Bringing all the data sets into R.
HDItable <- read.csv("data/HDR21-22Table 1.csv", skip =6, head = TRUE)
oecdAbbreviations <- read.csv("data/oecdAbbreviations.csv")
UnemploymentTotal2021 <- read.csv(header = TRUE, skip = 3, "data/2021WorldBankUnemploymentData.csv")
UnemploymentWomen2021 <- read.csv(header = TRUE, skip = 3, "data/2021WorldBankUnemploymentDataWomen.csv")
LiteracyRate2023 <- read.csv("data/LiteracyRate2023.csv")

Literacy <- select(LiteracyRate2023, "growthRate", "country", "region", "rank", "latestRate", "dataYear", "pop2023", "landAreaKm", "density")

#found colnames function here: https://www.projectpro.io/recipes/change-column-headers-of-dataframe-r#:~:text=How%20to%20change%20column%20headers%20of%20a%20data%2Dframe%20in,can%20be%20changed%20at%20once.
colnames(HDItable) <- c("HDI rank", "Country", "Human Development Index", "Empty", "Life Expectancy at Birth (years)", "Empty", "Expected Years of Schooling")

#This is the HDItable in a nice format
HDItable <- select(HDItable, "HDI rank", "Country", "Human Development Index", "Life Expectancy at Birth (years)", "Expected Years of Schooling") %>% 
  slice(1:195) %>% 
  drop_na()

UnemploymentTotal2 <- UnemploymentTotal2021 %>%
  select(Country.Name, Country.Code, X2021) %>%
  drop_na()

UnemploymentWomen2 <- UnemploymentWomen2021 %>%
  select(Country.Name, Country.Code, X2021) %>%
  drop_na()

#Only want the two columns with country names and codes.
Abbreviations <- oecdAbbreviations %>% 
  select("CODE", "Country")

#Now I want to join the oecd abbreviations to the countries in the HDItable.
HDItable2 <- HDItable %>%
  left_join(Abbreviations, by = contains("Country", "Country"))
unmatched <- as.list(HDItable2 %>% filter(is.na(CODE)) %>% select(Country))


#This part is not working out very nicely.
HDItable3 <- HDItable2 %>%
  left_join(UnemploymentTotal2, by = c("CODE" = "Country.Code")) %>%
  left_join(UnemploymentWomen2, by = c("CODE" = "Country.Code")) %>% 
  mutate(Total = X2021.x) %>%
    select(-(`X2021.x`)) %>%
  mutate(women = X2021.y) %>%
  select(-(X2021.y)) %>%
  select(-(Country.Name.x)) %>%
  select(-(Country.Name.y)) %>%
  left_join(Literacy, by = c("Country" = "country"))
write.csv(HDItable3, "data/wrangled.csv")

```

```{r}
Education_Literacy <- HDItable3 %>%
  select(region, Country, `Expected Years of Schooling`, latestRate) %>%
  drop_na() 

#The "as.numeric" numeric function: https://www.educative.io/answers/what-is-the-asnumeric-function-in-r
#What is happening with Europe?
Education_Literacy_cor <- Education_Literacy %>%
  group_by(region) %>%
  summarize(r_education = cor(latestRate, as.numeric(`Expected Years of Schooling`))) %>% 
left_join(Education_Literacy, Education_Literacy_cor, by = c("region" = "region"))


HDI_Literacy <-HDItable3 %>%
  select(region, Country, `Human Development Index`, latestRate) %>%
  drop_na()

HDI_Literacy_cor <- HDI_Literacy %>%
  group_by(region) %>%
  summarize(r_HDI = cor(latestRate, as.numeric(`Human Development Index`))) %>%
  left_join(HDI_Literacy, HDI_Literacy_cor, by = c("region" = "region")) %>%
  select(r_HDI, Country, `Human Development Index`)

HDI_Education <- left_join(Education_Literacy_cor, HDI_Literacy_cor, by = c("Country" = "Country")) %>%
  #negative means that education is a better predictor of literacy, positive means HDI is better.
  mutate(diff = r_HDI - r_education)

Density <- HDItable3 %>%
  select(Country, density)

HDI_Education2 <- HDI_Education %>%
  left_join(Density, HDI_Education, by = c("Country" = "Country"))




```


```{r}

data(gapminder)

world_map2 <- maps::map("world", plot = FALSE, fill = TRUE) %>%
  st_as_sf()

HDI_Education_map <- HDI_Education2 %>%
  right_join(world_map2, by = c("Country" = "ID"))


##Plotting difference between r_education and r_HDI on a world map
ggplot(HDI_Education_map, aes(geometry=geom, fill = diff)) +
  geom_sf() +
  theme_void() +
  labs(fill = "Difference"
       , title = "Where is HDI a better predictor of literacy rate than years of education?",
       subtitle = "Years: 2021, 2023"
       , caption = "Source: world bank data set") 


#One problem with this initial analysis is that it is quite granular. However, the map does bring to light the delineation between the "Global North" and "Global South." In the southern hemisphere, the "Global South," HDI and education are nearly equal predictors of literacy rate. This tracks with the idea that in so-called "under-developed" regions of the world---and HDI *is* lower in the Global South---obstacles to literacy are not purely educational. That is, in places where eduaction and HDI are comparable predictors of literacy, extra-educational aspects are predicting literacy rate. 

#Can I make a map of HDI in the world? Here it is!

HDI_map <- HDItable3 %>%
  select(Country, `Human Development Index`)

HDI_map2 <- HDI_map %>%
  right_join(world_map2, by = c("Country" = "ID"))

ggplot(HDI_map2, aes(geometry=geom, fill = as.numeric(`Human Development Index`))) +
  geom_sf() +
  theme_void() +
  labs(fill = "Human Development Index"
       , title = "HDI by country",
       subtitle = "Years: "
       , caption = "Source: World Bank data set") +
  scale_fill_distiller(palette = "Spectral")  
```


```{r}
#finding centroids for dotted cloropleth:

world_map3 <- world_map2 %>%
  inner_join(HDItable3, world_map2, by = c("ID" = "Country")) %>%
  select(geom, ID, region, density, latestRate) %>%
  filter(region == "Africa")

symbol_pos <- st_centroid(world_map3, of_largest_polygon = TRUE)

Dot_map <- inner_join(symbol_pos, HDItable3, by = c("ID" = "Country"))

ggplot(world_map3) +
  geom_sf() +
  geom_sf(data = symbol_pos, color = "blue")


ggplot(data = world_map3, aes(fill = latestRate)) +
  geom_sf(data = world_map3, color = "green") +
  geom_sf(data = symbol_pos,
          pch = 21,
          aes(size = density),
          fill = alpha("red", 0.7),
          col = "grey20") +
  labs(size = "density") +
  scale_size(range = c(1, 6))

#Where does this get the labels on the side from?
ggplot(data = world_map3, aes(x = latestRate, y = density)) +
             geom_point(size = 2) +
             geom_smooth(method = "lm") +
            #Labels and title for the scatter plot
             labs (y = "Literacy Rate",
                   x = "Population Density",
                   title = "Population Density vs. Literacy Rate")



```

```{r}
#SHREYA
library(readxl)
library(factoextra)
library(cluster)

#importing the dataset
GIIraw <- read_excel("data/GII.xlsx", col_names = TRUE, skip = 2)

#removing the na values plus selecting relevant columns
GII <- GIIraw %>% 
  select(...1, ...2, ...3, ...5) %>% 
  drop_na()

#renaming the columns
colnames(GII) <- c("HDI rank", "Country", "GII Value", "GII Rank")

#check the type of value for the column. apparently its charecter
class(GII$`GII Value`)
#hence converting to numeric before rounding the column
GII$`GII Value` <- as.numeric(GII$`GII Value`)
round(GII$`GII Value`, digits = 1)

HDI <- HDItable3 %>% 
  select("Country", "Human Development Index")

#joining the previously wrangled hdi values with GII valus
GIIHDI <- HDI %>% 
  left_join(GII, by = "Country")


#ELBOWPLOT
#standardising
matrix <- data.matrix(GIIHDI$`GII Value`)
matrix <- matrix[complete.cases(matrix), ]
matrix <- scale(matrix)

#clustering 
k_max <- 10
set.seed(180)
wss <- numeric(k_max)
for(k in 1:k_max) {
  km_res <- kmeans(matrix, k)
  wss[k] <- sum(km_res$withinss)
}

#plot the elbow curve
fviz_nbclust(matrix, kmeans, method = "wss", k.max = k_max, nstart = 25) +
  labs(title = "Elbow plot for GII values", x = "Number of clusters", y = "Within-cluster sum of squares") +
  geom_vline(xintercept = 3, linetype = "dashed", color = "red")


#cluster graph
# Add cluster assignment to the data frame
k_max <- 3
set.seed(180)
wss <- numeric(k_max)
for(k in 1:k_max) {
  km_res <- kmeans(matrix, k)
  wss[k] <- sum(km_res$withinss)
}

GIIHDI <- drop_na(GIIHDI)
GIIHDI$cluster <- as.factor(km_res$cluster)

# Plot the clusters
ggplot(GIIHDI, aes(x = `Human Development Index`, y = `GII Value`, color = cluster)) +
  geom_point(size = 3) +
  labs(title = "Cluster plot for GII values", x = "GII value") +
  theme_minimal()
```
```{r}
location_raw <- read.csv("data/location.csv", head = TRUE)

location <- location_raw %>% 
  select("country_code", "latitude", "longitude", "country") %>% 
  rename("Country" = "country")

GIIHDILocation <- GIIHDI %>% 
  left_join(location, by ="Country")

#cluster based on location

ggplot(GIIHDILocation, aes(x = longitude, y = latitude, fill = `HDI rank`)) +
  geom_point(alpha = 0.5)  + 
  scale_color_brewer(palette = "Set2")
```

```{r}
write.csv(GIIHDI, "GIIHDI.csv")
```


